### PR TITLE
Update portal ui

### PR DESCRIPTION
**Pull request by gndz07**
## Description

Update portal ui to be in line with the latest changes.

### CODE REVIEW

**Comment by immanuelfodor** [comment]
LGTM but could you please bump this to incorporate the latest UI fixes?

**Comment by gndz07** [comment]
@immanuelfodor yes I will update this 🙂

**Comment by svx** [comment]
@gndz07 is https://github.com/traefik/hub-apiportal-ui still OK, or do we need/should update the README?

**Comment by gndz07** [comment]
@svx the readme is still fine, it still works the same.

**Comment by gndz07** [comment]
@immanuelfodor @nmengin can we merge this PR?

**Comment by immanuelfodor** [comment]
Yes, please, all dependencies are out with today's release

**Review by mdeliatf — APPROVED** [review]
LGTM!

**Pull request merged**
